- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Aspid
  #- Atlas
  #- Amber
  - Bagel
  - Box
  #- Cluster
  #- Core
  #- Cog
  #- Fland
  #- Gate
  #- Loop
  #- Gemini
  - Marathon
  - Meta
  #- Omega
  #- Oasis
  #- Saltern
  #- Packed
  #- Reach
  #- Train